### ISSUE TITLE
Standardize join table nomenclature

### ISSUE THREAD

**Issue by davidmcclure** [sul-cidr/kb-api#10]
Right now we've got:
- `ocupation_person`
- `participation`

But both are linking people with other entities. Maybe clearer:
- `person_occupation`
- `person_event`

**Comment by kgeographer** [comment]
+1 

----- Original Message -----

**Comment by davidmcclure** [comment]
Actually, I wonder if it would make more sense here to just disable table pluralization altogether on ActiveRecord? Apparently we can do:

`ActiveRecord::Base.pluralize_table_names = false`

I know this is against the rails way, but there are a couple cases here where the plural names are confusing. Eg, say we've got a model called `PersonEvent`, a many-to-many join table that stores links between `Person` and `Event`. Rails would pluralize the name to:

`person_events`

Which, in effect, is:

`(person_event)s`

But it's confusing when you glance at the schema, because it looks like "person" is singular, but "events" is plural, etc.

**Comment by davidmcclure** [comment]
Eh, never mind, looks like it would take some real gymnastics to get Rails to play nice with singular table names. I did  standardize the names of the join tables, though. So, for example, now we've got models for:
- `Person`
- `PersonOccupation`
- `PersonEvent`

etc.
